/*
 * DupCheckPanel.java
 *
 * Created on October 12, 2006, 8:31 PM
 */

package offstage.wizards.modify;

import offstage.db.*;
import offstage.*;
import citibob.multithread.*;
import citibob.swing.typed.*;
import java.sql.*;
import citibob.swing.*;
import citibob.swing.table.*;

/**
 *
 * @author  citibob
 */
public class SearchViewer extends javax.swing.JPanel {

FullEntityDbModel entityDb;
EntityListTableModel dupsModel;

/** Creates new form DupCheckPanel */
public SearchViewer() {
	initComponents();
}

//public void initRuntime(Statement st,
//EntityListTableModel dupsModel, FullEntityDbModel entityDb,
//ActionRunner guiRunner, SwingerMap smap)
//{
//	this.dupsModel = dupsModel;
//	this.entityDb = entityDb;
//}

public void initRuntime(Statement st,
FrontApp fapp)
//FullEntityDbModel xentityDb,
//String idSql, String orderBy,
//final ActionRunner guiRunner, SwingerMap smap)
throws SQLException
{
	searchPanel.initRuntime(fapp);
	mainEntityPanel.initRuntime(st, fapp, fapp.getFullEntityDm());
	entityDb = fapp.getFullEntityDm();
//entityDb, smap);
//
//	dupsModel = new EntityListTableModel();
//	dupsModel.setRows(st, idSql, orderBy);
//	this.entityDb = xentityDb;
//	dupsTable.initRuntime(dupsModel);
//	DClickTableMouseListener dclick =
//		new DClickTableMouseListener(dupsTable) {
//		public void doubleClicked(final int row) {
//			guiRunner.doRun(new StRunnable() {
//			public void run(Statement st) throws Exception {
//				// Make sure it's selected in the GUI
//				dupsTable.getSelectionModel().setSelectionInterval(row, row);
//
//				// Process the selection
//				int entityid = getSelectedEntityID(dupsTable);
//				if (entityid < 0) return;
//				entityDb.setKey(entityid);
//				entityDb.doSelect(st);
//			}});
//		}};
//	
//	// Double-clicking will go to selected person
//	dupsTable.addMouseListener(dclick);
//	dclick.doubleClicked(0);		// There's at least one row here, select it.
//
}

int getSelectedEntityID(CitibobJTable searchResultsTable)
{
	int selected = searchResultsTable.getSelectedRow();
	if (selected < 0) return -1;
	int entityID = dupsModel.getEntityID(selected);
	return entityID;
}

public int getDisplayedEntityID()
{
	return entityDb.getEntityId();
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane2 = new javax.swing.JSplitPane();
        mainEntityPanel = new offstage.gui.MainEntityPanel();
        searchPanel = new offstage.gui.SimpleSearchPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setRightComponent(mainEntityPanel);

        jSplitPane2.setLeftComponent(searchPanel);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane2;
    private offstage.gui.MainEntityPanel mainEntityPanel;
    private offstage.gui.SimpleSearchPanel searchPanel;
    // End of variables declaration//GEN-END:variables

}
