/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * PersonPanel.java
 *
 * Created on February 9, 2005, 3:04 PM
 */

package offstage.gui;

import java.sql.*;
import citibob.jschema.*;
import offstage.db.FullEntityDbModel;

/**
 *
 * @author  citibob
 */
public class EntitySubPanel extends javax.swing.JPanel {
FullEntityDbModel dbModel;
	
	/** Creates new form PersonPanel */
	public EntitySubPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        info.clearthought.layout.TableLayout _tableLayoutInstance;
        info.clearthought.layout.TableLayout _tableLayoutInstance1;

        jLabel1 = new javax.swing.JLabel();
        address1 = new citibob.swing.typed.JTypedTextField();
        address2 = new citibob.swing.typed.JTypedTextField();
        city = new citibob.swing.typed.JTypedTextField();
        state = new citibob.swing.typed.JTypedTextField();
        zip = new citibob.swing.typed.JTypedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entityid = new citibob.swing.typed.JTypedTextField();
        lastupdated = new citibob.swing.typed.JTypedTextField();
        relprimarytypeid = new citibob.swing.typed.JKeyedComboBox();
        jLabel4 = new javax.swing.JLabel();

        _tableLayoutInstance = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance.setHGap(0);
        _tableLayoutInstance.setVGap(0);
        _tableLayoutInstance.setColumn(new double[]{info.clearthought.layout.TableLayout.PREFERRED,30,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        setLayout(_tableLayoutInstance);

        setPreferredSize(new java.awt.Dimension(200, 0));
        jLabel1.setText("Address");
        add(jLabel1, new info.clearthought.layout.TableLayoutConstraints(0, 0, 2, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        address1.setColName("address1");
        add(address1, new info.clearthought.layout.TableLayoutConstraints(0, 1, 2, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        address2.setColName("address2");
        add(address2, new info.clearthought.layout.TableLayoutConstraints(0, 2, 2, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        city.setColName("city");
        city.setPreferredSize(new java.awt.Dimension(120, 19));
        add(city, new info.clearthought.layout.TableLayoutConstraints(0, 3, 0, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        state.setColName("state");
        add(state, new info.clearthought.layout.TableLayoutConstraints(1, 3, 1, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        zip.setColName("zip");
        zip.setPreferredSize(new java.awt.Dimension(80, 19));
        add(zip, new info.clearthought.layout.TableLayoutConstraints(2, 3, 2, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        _tableLayoutInstance1 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance1.setHGap(0);
        _tableLayoutInstance1.setVGap(0);
        _tableLayoutInstance1.setColumn(new double[]{info.clearthought.layout.TableLayout.FILL,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance1.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        jPanel1.setLayout(_tableLayoutInstance1);

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jLabel3.setText("Last Modified");
        jPanel1.add(jLabel3, new info.clearthought.layout.TableLayoutConstraints(1, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        entityid.setEditable(false);
        entityid.setColName("entityid");
        jPanel1.add(entityid, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        lastupdated.setEditable(false);
        lastupdated.setColName("lastupdated");
        jPanel1.add(lastupdated, new info.clearthought.layout.TableLayoutConstraints(1, 1, 1, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        relprimarytypeid.setColName("relprimarytypeid");
        relprimarytypeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relprimarytypeidActionPerformed(evt);
            }
        });

        jPanel1.add(relprimarytypeid, new info.clearthought.layout.TableLayoutConstraints(0, 3, 1, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jLabel4.setText("Relationship to Primary");
        jPanel1.add(jLabel4, new info.clearthought.layout.TableLayoutConstraints(0, 2, 1, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(jPanel1, new info.clearthought.layout.TableLayoutConstraints(0, 4, 2, 4, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

    }
    // </editor-fold>//GEN-END:initComponents

private void relprimarytypeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relprimarytypeidActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_relprimarytypeidActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private citibob.swing.typed.JTypedTextField address1;
    private citibob.swing.typed.JTypedTextField address2;
    private citibob.swing.typed.JTypedTextField city;
    private citibob.swing.typed.JTypedTextField entityid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private citibob.swing.typed.JTypedTextField lastupdated;
    private citibob.swing.typed.JKeyedComboBox relprimarytypeid;
    private citibob.swing.typed.JTypedTextField state;
    private citibob.swing.typed.JTypedTextField zip;
    // End of variables declaration//GEN-END:variables
	
}
