/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * EntityPanel.java
 *
 * Created on June 5, 2005, 9:48 AM
 */

package offstage.gui;


import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.sql.*;
import citibob.jschema.*;
import citibob.multithread.*;
import citibob.jschema.swing.*;
//import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import java.awt.*;
import java.awt.event.*;
import offstage.FrontApp;
import offstage.db.FullEntityDbModel;
/**
 *
 * @author  citibob
 */
public class EntityPanel extends javax.swing.JPanel {
	
	/** Creates new form EntityPanel */
	public EntityPanel() {
		initComponents();
	}

	EntityPanel getThis() { return this; }
	
	public void initRuntime(Statement st, ActionRunner runner, FullEntityDbModel dm, SwingerMap smap)
	throws java.sql.SQLException
	{
		personPanel.initRuntime(st, runner, dm, smap);
		orgPanel.initRuntime(st, runner, dm, smap);
		donationsPanel.initRuntime(st, dm.getDonationSb(),
			new String[] {"Type", "Date", "Amount"},
			new String[] {"groupid", "date", "amount"}, smap);
		eventsPanel.initRuntime(st, dm.getEventsSb(),
			new String[] {"Type", "Role"},
			new String[] {"groupid", "role"}, smap);
		notesPanel.initRuntime(st, dm.getNotesSb(),
			new String[] {"Type", "Date", "Note"},
			new String[] {"groupid", "date", "note"}, smap);
		dm.addListener(new FullEntityDbModel.Adapter() {
		public void entityTypeChanged(int type) {
			CardLayout cl = (CardLayout)(basicPanel.getLayout());
			switch(type) {
				case FullEntityDbModel.ORG :
					cl.show(basicPanel, "org");
				break;
				case FullEntityDbModel.PERSON :
					cl.show(basicPanel, "person");
				break;
			}
		}});
	}	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        info.clearthought.layout.TableLayout _tableLayoutInstance;

        basicPanel = new javax.swing.JPanel();
        personPanel = new offstage.gui.PersonPanel();
        orgPanel = new offstage.gui.OrgPanel();
        groupPanels = new javax.swing.JTabbedPane();
        donationsPanel = new offstage.gui.GroupPanel();
        eventsPanel = new offstage.gui.GroupPanel();
        notesPanel = new offstage.gui.GroupPanel();

        _tableLayoutInstance = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance.setHGap(0);
        _tableLayoutInstance.setVGap(0);
        _tableLayoutInstance.setColumn(new double[]{535});
        _tableLayoutInstance.setRow(new double[]{330,info.clearthought.layout.TableLayout.FILL,info.clearthought.layout.TableLayout.PREFERRED});
        setLayout(_tableLayoutInstance);

        basicPanel.setLayout(new java.awt.CardLayout());

        basicPanel.add(personPanel, "person");

        basicPanel.add(orgPanel, "org");

        add(basicPanel, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        groupPanels.setPreferredSize(new java.awt.Dimension(458, 200));
        groupPanels.addTab("Donations", donationsPanel);

        groupPanels.addTab("Events", eventsPanel);

        groupPanels.addTab("Notes", notesPanel);

        add(groupPanels, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicPanel;
    private offstage.gui.GroupPanel donationsPanel;
    private offstage.gui.GroupPanel eventsPanel;
    private javax.swing.JTabbedPane groupPanels;
    private offstage.gui.GroupPanel notesPanel;
    private offstage.gui.OrgPanel orgPanel;
    private offstage.gui.PersonPanel personPanel;
    // End of variables declaration//GEN-END:variables

//	public static void main(String[] args) throws Exception
//    {
//
//
//		FrontApp app = new FrontApp();
//		FullEntityDbModel dm = app.getFullEntityDm();
//		Statement st = app.getPool().checkout().createStatement();
//
//		dm.setKey(139208);
//		dm.doSelect(st);
//		System.out.println("Type = " + dm.getEntityType());
//
//		EntityPanel personPanel = new EntityPanel();
//		personPanel.initRuntime(st, dm);//personRM, dm.getPhonesSb());
//
//		
//		
//	    JFrame frame = new JFrame();
//	    frame.getContentPane().add(personPanel);
//		frame.pack();
//	    frame.setVisible(true);
//		System.out.println("Done");
//    }
	
}
