/*
 * EntitySelectorDialog.java
 *
 * Created on June 24, 2007, 6:55 PM
 */

package offstage.gui;

import java.awt.*;

/**
 *
 * @author  citibob
 */
public class EntitySelectorDialog extends javax.swing.JDialog
{
	public int getEntityID() { return (Integer)panel.getValue(); }
	
	/** Creates new form EntitySelectorDialog */
	public EntitySelectorDialog(Frame frame, boolean modal)
	{
		super(frame, modal);
		
		initComponents();
		panel.initRuntime(app);
		
		panel.getSearchTable().addMouseListener(new java.awt.event.MouseAdapter() {
		public void mouseClicked(java.awt.event.MouseEvent e) {
//		app.runGui(EntitySelectorPanel.this, new StRunnable() {
//		public void run(Statement st) throws Exception {
			if( e.getClickCount() != 2 ) return;
			setVisible(false);
//		}});
		}});

//	// Double-clicking will go to selected person
//	searchResultsTable.addMouseListener(new DClickTableMouseListener(searchResultsTable) {
//	public void doubleClicked(final int row) {
//		app.runGui(EntitySelectorPanel.this, new StRunnable() {
//		public void run(Statement st) throws Exception {
//			// Make sure it's selected in the GUI
//			searchResultsTable.getSelectionModel().setSelectionInterval(row, row);
//
//			// Process the selection
//			int entityid = getSelectedEntityID();
//			if (entityid < 0) return;
//			dm.setKey(entityid);
//			dm.doSelect(st);
//		}});
//	}});
//
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        panel = new offstage.gui.EntitySelectorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
	{//GEN-HEADEREND:event_formWindowClosing
		setVisible(false);
// TODO add your handling code here:
	}//GEN-LAST:event_formWindowClosing
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				EntitySelectorDialog esd = new EntitySelectorDialog(null, true);
				esd.setVisible(true);
				System.out.println(esd.getEntityID());
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.gui.EntitySelectorPanel panel;
    // End of variables declaration//GEN-END:variables
	
}
