/*
 * MainEntityPanel.java
 *
 * Created on October 12, 2006, 8:33 PM
 */

package offstage.gui;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.sql.*;
import citibob.jschema.*;
import citibob.multithread.*;
import citibob.jschema.swing.*;
//import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import java.awt.*;
import java.awt.event.*;
import offstage.FrontApp;
import offstage.db.FullEntityDbModel;

/**
 *
 * @author  citibob
 */
public class MainEntityPanel extends javax.swing.JPanel {

    /** Creates new form MainEntityPanel */
    public MainEntityPanel() {
        initComponents();
    }

public void initRuntime(Statement st, ActionRunner runner, FullEntityDbModel dm, SwingerMap smap)
throws SQLException
{
	personPanel.initRuntime(st, runner, dm, smap);
	orgPanel.initRuntime(st, runner, dm, smap);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        personPanel = new offstage.gui.PersonPanel();
        orgPanel = new offstage.gui.OrgPanel();

        setLayout(new java.awt.CardLayout());

        add(personPanel, "person");

        add(orgPanel, "org");

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.gui.OrgPanel orgPanel;
    private offstage.gui.PersonPanel personPanel;
    // End of variables declaration//GEN-END:variables

}
