/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * FrontGui.java
 *
 * Created on July 13, 2005, 10:52 PM
 */

package offstage.gui;
import java.sql.*;
import java.util.prefs.*;
import citibob.swing.prefs.*;
import citibob.jschema.swing.*;
import offstage.FrontApp;
import offstage.EQueryBrowserApp;

/**
 *
 * @author  citibob
 */
public class OffstageGui extends javax.swing.JFrame {
	
	/** Creates new form FrontGui */
	public OffstageGui() {
		initComponents();
	}

	public void initRuntime(final FrontApp app)
	throws java.sql.SQLException
	{
		Connection dbb = null;
		Statement st = null;
		try {
			dbb = app.getPool().checkout();
			st = dbb.createStatement();
			EQueryBrowserApp eapp = app.getEqueryBrowserApp();
			people.initRuntime(st, app);
			queries.initRuntime(app);
			mailings.initRuntime(st, app); //st, eapp.getMailingidsSb(), app.getMailingsDm());

			JSchemaWidgetTree.initWithStatement(this, st);

			app.addListener(new FrontApp.Adapter() {
			public void screenChanged() {
				switch(app.getScreen()) {
					case FrontApp.PEOPLE_SCREEN :
						tabs.setSelectedIndex(0);
					break;
					case FrontApp.QUERIES_SCREEN :
						tabs.setSelectedIndex(1);
					break;
					case FrontApp.MAILINGS_SCREEN :
						tabs.setSelectedIndex(2);
					break;
				}
			}});

			// Mess with preferences
			Preferences prefs = Preferences.userNodeForPackage(this.getClass());
			prefs = prefs.node("OmniGui");
			new SwingPrefs().setPrefs(this, "", prefs);
		} finally {
			st.close();
			app.getPool().checkin(dbb);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tabs = new javax.swing.JTabbedPane();
        people = new offstage.gui.EditorPanel();
        queries = new offstage.gui.EQueryBrowser();
        mailings = new offstage.gui.MailingsEditor();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        tabs.addTab("People", people);

        tabs.addTab("Queries", queries);

        tabs.addTab("Mailings", mailings);

        getContentPane().add(tabs, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        miQuit.setText("Quit");
        jMenu1.add(miQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) throws Exception
    {
		FrontApp app = new FrontApp();
		OffstageGui gui = new OffstageGui();
		gui.initRuntime(app);
	    gui.setVisible(true);
    }
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private offstage.gui.MailingsEditor mailings;
    private javax.swing.JMenuItem miQuit;
    private offstage.gui.EditorPanel people;
    private offstage.gui.EQueryBrowser queries;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
	
}
