/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2007 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * PersonPanel.java
 *
 * Created on February 9, 2005, 8:18 PM
 */

package offstage.gui;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.sql.*;
import citibob.multithread.*;
import citibob.jschema.*;
import citibob.jschema.swing.*;
//import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import offstage.FrontApp;
import offstage.db.FullEntityDbModel;

/**
 *
 * @author  citibob
 */
public class OrgPanel 
extends javax.swing.JPanel {
    
    SchemaRowModel model;	// The RowModel (which uses the schema)
	//SchemaBuf phonesSb;
	//TableModel family;
	FullEntityDbModel dm;
//	Statement st;
//	ActionRunner runner;
	citibob.app.App app;
	
//    public static void main(String[] args) throws Exception
//    {
//
//
//		FrontApp app = new FrontApp();
//		FullEntityDbModel dm = app.getFullEntityDm();
//		ConnPool pool = app.getPool();
//		Statement st = app.getPool().checkout().createStatement();
//
////		dm.setKey(126341);
////		dm.doSelect(st);
////		System.out.println("Type = " + dm.getEntityType());
//
//		OrgPanel orgPanel = new OrgPanel();
//		orgPanel.initRuntime(st, dm);//orgRM, dm.getPhonesSb());
//
//		
//		
//	    JFrame frame = new JFrame();
//	    frame.getContentPane().add(orgPanel);
//		JSchemaWidgetTree.bindToPool(frame, pool);
//		frame.pack();
//	    frame.setVisible(true);
//		System.out.println("Done");
//    }
    
	/** Creates new form PersonPanel */
	public OrgPanel() {
		initComponents();
	}
	
	public void initRuntime(Statement st, citibob.app.App app, FullEntityDbModel dm)
	throws java.sql.SQLException
	{
		this.app = app;
		this.dm = dm;
		//SchemaBufRowModel model = dm.getOrgRm();
		SchemaBufRowModel model = new SchemaBufRowModel(dm.getOrgSb());
		//SchemaBuf phonesSb = dm.getPhonesSb();

		//this.phonesSb = phonesSb;
		this.model = model;
		
		TypedWidgetBinder.bindRecursive(this, model, app.getSwingerMap());
		//JSchemaWidgetTree.bindToPool(this, pool);
		//JEnum phoneEnum = (JEnum)dm.getPhonesSb().getSchema().getCol("groupid").getType();
		phonePanel.initRuntime(st, dm.getPhonesSb(),
			new String[] {"Type", "Number"},
			new String[] {"groupid", "phone"}, app.getSwingerMap());
		// phonesTable.setModel(new ColPermuteTableModel(phonesSb,
		//	new String[] {"Type", "Phone"},
		//	new String[] {"groupid", "phone"}));
//		familyTable.setModel(dm.getFamily());
		familyTable.initRuntime(dm.getOrgDb().getFamily());
		//familyTable.initRuntime(dm.getFamily());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FamilyPane = new javax.swing.JPanel();
        FamilyScrollPanel = new javax.swing.JScrollPane();
        familyTable = new offstage.gui.FamilyTable();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        gotoEntity = new javax.swing.JButton();
        clearFamily = new javax.swing.JButton();
        phonePanel = new offstage.gui.GroupPanel();
        jLabel11 = new javax.swing.JLabel();
        orgPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new citibob.swing.typed.JTypedTextField();
        entitySubPanel1 = new offstage.gui.EntitySubPanel();

        setLayout(new java.awt.GridBagLayout());

        FamilyPane.setLayout(new java.awt.BorderLayout());

        FamilyScrollPanel.setPreferredSize(new java.awt.Dimension(300, 64));
        familyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FamilyScrollPanel.setViewportView(familyTable);

        FamilyPane.add(FamilyScrollPanel, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Family Members");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        FamilyPane.add(jLabel8, java.awt.BorderLayout.NORTH);

        gotoEntity.setText("Go");
        gotoEntity.setToolTipText("Edit Selected Family Member");
        gotoEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoEntityActionPerformed(evt);
            }
        });

        jToolBar1.add(gotoEntity);

        clearFamily.setText("Make Head");
        clearFamily.setToolTipText("Make this person head of his/her own family.");
        clearFamily.setPreferredSize(new java.awt.Dimension(80, 27));
        clearFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFamilyActionPerformed(evt);
            }
        });

        jToolBar1.add(clearFamily);

        FamilyPane.add(jToolBar1, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.7;
        add(FamilyPane, gridBagConstraints);

        phonePanel.setPreferredSize(new java.awt.Dimension(453, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        add(phonePanel, gridBagConstraints);

        jLabel11.setText("Phone Numbers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel11, gridBagConstraints);

        orgPanel.setLayout(new java.awt.GridBagLayout());

        NamePanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Organization Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        NamePanel.add(jLabel2, gridBagConstraints);

        name.setColName("name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        NamePanel.add(name, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        orgPanel.add(NamePanel, gridBagConstraints);

        entitySubPanel1.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        orgPanel.add(entitySubPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        add(orgPanel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

	private void clearFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFamilyActionPerformed
		app.runGui(this, new StRunnable() { public void run(Statement st) throws Exception {
			dm.getEntitySb().clearFamily();
			dm.doUpdate(st);
			dm.doSelect(st);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_clearFamilyActionPerformed

	private void gotoEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoEntityActionPerformed
		app.runGui(this, new StRunnable() { public void run(Statement st) throws Exception {
			int selected = familyTable.getSelectedRow();
			int entityID = dm.getEntity().getFamily().getEntityID(selected);
			dm.setKey(entityID);
			dm.doSelect(st);
		}});
	}//GEN-LAST:event_gotoEntityActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FamilyPane;
    private javax.swing.JScrollPane FamilyScrollPanel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JButton clearFamily;
    private offstage.gui.EntitySubPanel entitySubPanel1;
    private offstage.gui.FamilyTable familyTable;
    private javax.swing.JButton gotoEntity;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToolBar jToolBar1;
    private citibob.swing.typed.JTypedTextField name;
    private javax.swing.JPanel orgPanel;
    private offstage.gui.GroupPanel phonePanel;
    // End of variables declaration//GEN-END:variables
	// --------------------------------------------------------------

}
