/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * PersonPanel.java
 *
 * Created on February 9, 2005, 8:18 PM
 */

package offstage.gui;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.sql.*;
import citibob.multithread.*;
import citibob.jschema.*;
import citibob.jschema.swing.*;
//import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import offstage.FrontApp;
import offstage.db.FullEntityDbModel;

/**
 *
 * @author  citibob
 */
public class OrgPanel 
extends javax.swing.JPanel {
    
    SchemaRowModel model;	// The RowModel (which uses the schema)
	//SchemaBuf phonesSb;
	//TableModel family;
	FullEntityDbModel dm;
//	Statement st;
	ActionRunner runner;
	
//    public static void main(String[] args) throws Exception
//    {
//
//
//		FrontApp app = new FrontApp();
//		FullEntityDbModel dm = app.getFullEntityDm();
//		ConnPool pool = app.getPool();
//		Statement st = app.getPool().checkout().createStatement();
//
////		dm.setKey(126341);
////		dm.doSelect(st);
////		System.out.println("Type = " + dm.getEntityType());
//
//		OrgPanel orgPanel = new OrgPanel();
//		orgPanel.initRuntime(st, dm);//orgRM, dm.getPhonesSb());
//
//		
//		
//	    JFrame frame = new JFrame();
//	    frame.getContentPane().add(orgPanel);
//		JSchemaWidgetTree.bindToPool(frame, pool);
//		frame.pack();
//	    frame.setVisible(true);
//		System.out.println("Done");
//    }
    
	/** Creates new form PersonPanel */
	public OrgPanel() {
		initComponents();
	}
	
	public void initRuntime(Statement st, ActionRunner runner, FullEntityDbModel dm, SwingerMap smap)
	throws java.sql.SQLException
	{
		this.runner = runner;
		this.dm = dm;
		//SchemaBufRowModel model = dm.getOrgRm();
		SchemaBufRowModel model = new SchemaBufRowModel(dm.getOrgSb());
		//SchemaBuf phonesSb = dm.getPhonesSb();

		//this.phonesSb = phonesSb;
		this.model = model;
		
		TypedWidgetBinder.bindRecursive(this, model, smap);
		//JSchemaWidgetTree.bindToPool(this, pool);
		//JEnum phoneEnum = (JEnum)dm.getPhonesSb().getSchema().getCol("groupid").getType();
		phonePanel.initRuntime(st, dm.getPhonesSb(),
			new String[] {"Type", "Number"},
			new String[] {"groupid", "phone"}, smap);
		// phonesTable.setModel(new ColPermuteTableModel(phonesSb,
		//	new String[] {"Type", "Phone"},
		//	new String[] {"groupid", "phone"}));
//		familyTable.setModel(dm.getFamily());
		familyTable.initRuntime(dm.getOrgDb().getFamily());
		//familyTable.initRuntime(dm.getFamily());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        info.clearthought.layout.TableLayout _tableLayoutInstance;
        info.clearthought.layout.TableLayout _tableLayoutInstance5;

        entitySubPanel1 = new offstage.gui.EntitySubPanel();
        FamilyPane = new javax.swing.JPanel();
        FamilyScrollPanel = new javax.swing.JScrollPane();
        familyTable = new offstage.gui.FamilyTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gotoEntity = new javax.swing.JButton();
        clearFamily = new javax.swing.JButton();
        NamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new citibob.swing.typed.JTypedTextField();
        phonePanel = new offstage.gui.GroupPanel();
        jLabel11 = new javax.swing.JLabel();

        _tableLayoutInstance = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance.setHGap(0);
        _tableLayoutInstance.setVGap(0);
        _tableLayoutInstance.setColumn(new double[]{200,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance.setRow(new double[]{info.clearthought.layout.TableLayout.FILL,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        setLayout(_tableLayoutInstance);

        entitySubPanel1.setPreferredSize(null);
        add(entitySubPanel1, new info.clearthought.layout.TableLayoutConstraints(0, 3, 0, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        FamilyPane.setLayout(new java.awt.BorderLayout());

        FamilyScrollPanel.setPreferredSize(new java.awt.Dimension(300, 64));
        familyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FamilyScrollPanel.setViewportView(familyTable);

        FamilyPane.add(FamilyScrollPanel, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Family Members");
        FamilyPane.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        gotoEntity.setText("Go");
        gotoEntity.setToolTipText("Edit Selected Family Member");
        gotoEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoEntityActionPerformed(evt);
            }
        });

        jPanel2.add(gotoEntity);

        clearFamily.setText("Make Head");
        clearFamily.setToolTipText("Make this person head of his/her own family.");
        clearFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFamilyActionPerformed(evt);
            }
        });

        jPanel2.add(clearFamily);

        FamilyPane.add(jPanel2, java.awt.BorderLayout.EAST);

        add(FamilyPane, new info.clearthought.layout.TableLayoutConstraints(2, 0, 2, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        _tableLayoutInstance5 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance5.setHGap(0);
        _tableLayoutInstance5.setVGap(0);
        _tableLayoutInstance5.setColumn(new double[]{info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance5.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        NamePanel.setLayout(_tableLayoutInstance5);

        jLabel2.setText("Organization Name");
        NamePanel.add(jLabel2, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        name.setColName("name");
        NamePanel.add(name, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(NamePanel, new info.clearthought.layout.TableLayoutConstraints(0, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        phonePanel.setPreferredSize(new java.awt.Dimension(453, 100));
        add(phonePanel, new info.clearthought.layout.TableLayoutConstraints(1, 3, 2, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jLabel11.setText("Phone Numbers");
        add(jLabel11, new info.clearthought.layout.TableLayoutConstraints(1, 2, 2, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.TOP));

    }
    // </editor-fold>//GEN-END:initComponents

	private void clearFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFamilyActionPerformed
		runner.doRun(new StRunnable() { public void run(Statement st) throws Exception {
			dm.getEntitySb().clearFamily();
			dm.doUpdate(st);
			dm.doSelect(st);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_clearFamilyActionPerformed

	private void gotoEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoEntityActionPerformed
		runner.doRun(new StRunnable() { public void run(Statement st) throws Exception {
			int selected = familyTable.getSelectedRow();
			int entityID = dm.getEntity().getFamily().getEntityID(selected);
			dm.setKey(entityID);
			dm.doSelect(st);
		}});
	}//GEN-LAST:event_gotoEntityActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FamilyPane;
    private javax.swing.JScrollPane FamilyScrollPanel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JButton clearFamily;
    private offstage.gui.EntitySubPanel entitySubPanel1;
    private offstage.gui.FamilyTable familyTable;
    private javax.swing.JButton gotoEntity;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private citibob.swing.typed.JTypedTextField name;
    private offstage.gui.GroupPanel phonePanel;
    // End of variables declaration//GEN-END:variables
	// --------------------------------------------------------------

}
