/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * PersonPanel.java
 *
 * Created on February 9, 2005, 8:18 PM
 */

package offstage.gui;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.jschema.*;
import citibob.jschema.swing.*;
import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import offstage.FrontApp;
import offstage.db.FullEntityDbModel;
import citibob.multithread.*;

/**
 *
 * @author  citibob
 */
public class PersonPanel 
extends javax.swing.JPanel {
    
    SchemaRowModel model;	// The RowModel (which uses the schema)
	//SchemaBuf phonesSb;
	//TableModel family;
	FullEntityDbModel dm;
//	Statement st;
	ActionRunner runner;
	
//    public static void main(String[] args) throws Exception
//    {
//
//
//		FrontApp app = new FrontApp();
//		FullEntityDbModel dm = app.getFullEntityDm();
//		Statement st = app.createStatement();
//
//		dm.setKey(146141);
//		dm.doSelect(st);
//		System.out.println("Type = " + dm.getEntityType());
//
//		PersonPanel personPanel = new PersonPanel();
//		personPanel.initRuntime(st, dm);//personRM, dm.getPhonesSb());
//
//		
//		
//	    JFrame frame = new JFrame();
//	    frame.getContentPane().add(personPanel);
//		frame.pack();
//	    frame.setVisible(true);
//		System.out.println("Done");
//    }
    
	/** Creates new form PersonPanel */
	public PersonPanel() {
		initComponents();
		genderButtonGroup.add("M", maleButton);
		genderButtonGroup.add("F", femaleButton);
		genderButtonGroup.add(null, unknownGenderButton);
		
		
		familyTable.addMouseListener(new DClickTableMouseListener(familyTable) {
		public void doubleClicked(final int row) {
			runner.doRun(new StRunnable() {
			public void run(Statement st) throws Exception {
				// Make sure it's selected in the GUI
				familyTable.getSelectionModel().setSelectionInterval(row, row);

				// Process the selection
				int selected = familyTable.getSelectedRow();
				if (selected < 0) return;
				int entityID = dm.getEntity().getFamily().getEntityID(selected);
				dm.setKey(entityID);
				dm.doSelect(st);
			}});
		}});

	}
	
	public void initRuntime(Statement st, ActionRunner runner, FullEntityDbModel dm)
	throws java.sql.SQLException
	{
		this.runner = runner;
		this.dm = dm;
		//SchemaBufRowModel model = dm.getPersonRm();
		SchemaBufRowModel model = new SchemaBufRowModel(dm.getPersonSb());
		//SchemaBuf phonesSb = dm.getPhonesSb();

		//this.phonesSb = phonesSb;
		this.model = model;
		
		JSchemaWidgetTree.bindToSchemaRow(this, model);
		genderButtonGroup.bind(model);
		phonePanel.initRuntime(st, dm.getPhonesSb(), "phoneids",
			new String[] {"Number"},
			new String[] {"phone"});
//		phonesTable.initRuntime(dm.getPhonesSb());
//		this.addPhoneType.setModel(new GroupTypeKeyedModel(st, "phoneids"));
		// phonesTable.setModel(new ColPermuteTableModel(phonesSb,
		//	new String[] {"Type", "Phone"},
		//	new String[] {"groupid", "phone"}));
//		familyTable.setModel(dm.getFamily());
		familyTable.initRuntime(dm.getPersonDb().getFamily());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        info.clearthought.layout.TableLayout _tableLayoutInstance;
        info.clearthought.layout.TableLayout _tableLayoutInstance1;
        info.clearthought.layout.TableLayout _tableLayoutInstance2;
        info.clearthought.layout.TableLayout _tableLayoutInstance3;
        info.clearthought.layout.TableLayout _tableLayoutInstance4;

        genderButtonGroup = new citibob.jschema.swing.JSchemaKeyedButtonGroup();
        FirstMiddleLast = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salutation = new citibob.jschema.swing.JSchemaTextField();
        firstname = new citibob.jschema.swing.JSchemaTextField();
        middlename = new citibob.jschema.swing.JSchemaTextField();
        lastname = new citibob.jschema.swing.JSchemaTextField();
        entitySubPanel1 = new offstage.gui.EntitySubPanel();
        MiscInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        occupation = new citibob.jschema.swing.JSchemaTextField();
        dob = new citibob.jschema.swing.JSchemaTextField();
        title = new citibob.jschema.swing.JSchemaTextField();
        email = new citibob.jschema.swing.JSchemaTextField();
        Gender = new javax.swing.JPanel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        unknownGenderButton = new javax.swing.JRadioButton();
        FamilyPane = new javax.swing.JPanel();
        FamilyScrollPanel = new javax.swing.JScrollPane();
        familyTable = new offstage.gui.FamilyTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        isPrimaryIndicator1 = new offstage.gui.IsPrimaryIndicator();
        clearFamily = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        customaddressto = new citibob.jschema.swing.JSchemaTextField();
        phonePanel = new offstage.gui.GroupPanel();
        jLabel11 = new javax.swing.JLabel();

        genderButtonGroup.setColName("gender");

        _tableLayoutInstance = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance.setHGap(0);
        _tableLayoutInstance.setVGap(0);
        _tableLayoutInstance.setColumn(new double[]{200,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.FILL});
        setLayout(_tableLayoutInstance);

        _tableLayoutInstance1 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance1.setHGap(0);
        _tableLayoutInstance1.setVGap(0);
        _tableLayoutInstance1.setColumn(new double[]{40,info.clearthought.layout.TableLayout.FILL,30,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance1.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        FirstMiddleLast.setLayout(_tableLayoutInstance1);

        jLabel1.setText("First");
        FirstMiddleLast.add(jLabel1, new info.clearthought.layout.TableLayoutConstraints(1, 0, 1, 0, info.clearthought.layout.TableLayout.LEFT, info.clearthought.layout.TableLayout.FULL));

        jLabel2.setText("Middle");
        FirstMiddleLast.add(jLabel2, new info.clearthought.layout.TableLayoutConstraints(2, 0, 2, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jLabel3.setText("Last");
        FirstMiddleLast.add(jLabel3, new info.clearthought.layout.TableLayoutConstraints(3, 0, 3, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        salutation.setColName("salutation");
        FirstMiddleLast.add(salutation, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        firstname.setColName("firstname");
        FirstMiddleLast.add(firstname, new info.clearthought.layout.TableLayoutConstraints(1, 1, 1, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        middlename.setColName("middlename");
        FirstMiddleLast.add(middlename, new info.clearthought.layout.TableLayoutConstraints(2, 1, 2, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        lastname.setColName("lastname");
        lastname.setPreferredSize(new java.awt.Dimension(10, 15));
        FirstMiddleLast.add(lastname, new info.clearthought.layout.TableLayoutConstraints(3, 1, 3, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(FirstMiddleLast, new info.clearthought.layout.TableLayoutConstraints(0, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        entitySubPanel1.setPreferredSize(null);
        add(entitySubPanel1, new info.clearthought.layout.TableLayoutConstraints(0, 2, 0, 4, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        _tableLayoutInstance2 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance2.setHGap(0);
        _tableLayoutInstance2.setVGap(0);
        _tableLayoutInstance2.setColumn(new double[]{info.clearthought.layout.TableLayout.MINIMUM,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance2.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        MiscInfo.setLayout(_tableLayoutInstance2);

        jLabel4.setText("Occupation");
        MiscInfo.add(jLabel4, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.RIGHT, info.clearthought.layout.TableLayout.FULL));

        jLabel5.setText("DOB");
        MiscInfo.add(jLabel5, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.RIGHT, info.clearthought.layout.TableLayout.FULL));

        jLabel6.setText("Title");
        MiscInfo.add(jLabel6, new info.clearthought.layout.TableLayoutConstraints(0, 2, 0, 2, info.clearthought.layout.TableLayout.RIGHT, info.clearthought.layout.TableLayout.FULL));

        jLabel7.setText("Email");
        MiscInfo.add(jLabel7, new info.clearthought.layout.TableLayoutConstraints(0, 3, 0, 3, info.clearthought.layout.TableLayout.RIGHT, info.clearthought.layout.TableLayout.FULL));

        occupation.setColName("occupation");
        MiscInfo.add(occupation, new info.clearthought.layout.TableLayoutConstraints(1, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        dob.setColName("dob");
        MiscInfo.add(dob, new info.clearthought.layout.TableLayoutConstraints(1, 1, 1, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        title.setColName("title");
        MiscInfo.add(title, new info.clearthought.layout.TableLayoutConstraints(1, 2, 1, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        email.setColName("email");
        MiscInfo.add(email, new info.clearthought.layout.TableLayoutConstraints(1, 3, 1, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(MiscInfo, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        _tableLayoutInstance3 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance3.setHGap(0);
        _tableLayoutInstance3.setVGap(0);
        _tableLayoutInstance3.setColumn(new double[]{info.clearthought.layout.TableLayout.PREFERRED});
        _tableLayoutInstance3.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.PREFERRED});
        Gender.setLayout(_tableLayoutInstance3);

        maleButton.setText("Male");
        Gender.add(maleButton, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        femaleButton.setText("Female");
        Gender.add(femaleButton, new info.clearthought.layout.TableLayoutConstraints(0, 1, 0, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.TOP));

        unknownGenderButton.setText("Unknown");
        Gender.add(unknownGenderButton, new info.clearthought.layout.TableLayoutConstraints(0, 2, 0, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(Gender, new info.clearthought.layout.TableLayoutConstraints(1, 1, 1, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.TOP));

        FamilyPane.setLayout(new java.awt.BorderLayout());

        FamilyPane.setPreferredSize(new java.awt.Dimension(418, 132));
        FamilyScrollPanel.setPreferredSize(new java.awt.Dimension(300, 64));
        familyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FamilyScrollPanel.setViewportView(familyTable);

        FamilyPane.add(FamilyScrollPanel, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Family Members");
        FamilyPane.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        isPrimaryIndicator1.setText("Primary Family Contact");
        isPrimaryIndicator1.setEnabled(false);
        jPanel2.add(isPrimaryIndicator1);

        clearFamily.setText("Make Primary");
        clearFamily.setToolTipText("");
        clearFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFamilyActionPerformed(evt);
            }
        });

        jPanel2.add(clearFamily);

        FamilyPane.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(FamilyPane, new info.clearthought.layout.TableLayoutConstraints(2, 0, 2, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        _tableLayoutInstance4 = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance4.setHGap(0);
        _tableLayoutInstance4.setVGap(0);
        _tableLayoutInstance4.setColumn(new double[]{info.clearthought.layout.TableLayout.PREFERRED,info.clearthought.layout.TableLayout.FILL});
        _tableLayoutInstance4.setRow(new double[]{info.clearthought.layout.TableLayout.PREFERRED});
        jPanel3.setLayout(_tableLayoutInstance4);

        jLabel10.setText("To");
        jPanel3.add(jLabel10, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        customaddressto.setColName("customaddressto");
        jPanel3.add(customaddressto, new info.clearthought.layout.TableLayoutConstraints(1, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        add(jPanel3, new info.clearthought.layout.TableLayoutConstraints(0, 2, 0, 2, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.TOP));

        phonePanel.setPreferredSize(new java.awt.Dimension(453, 150));
        add(phonePanel, new info.clearthought.layout.TableLayoutConstraints(1, 4, 2, 4, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jLabel11.setText("Phone Numbers");
        add(jLabel11, new info.clearthought.layout.TableLayoutConstraints(1, 3, 2, 3, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

    }
    // </editor-fold>//GEN-END:initComponents

	private void clearFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFamilyActionPerformed
		runner.doRun(new StRunnable() { public void run(Statement st) throws Exception {
			dm.getEntitySb().clearFamily();
			dm.doUpdate(st);
			dm.doSelect(st);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_clearFamilyActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FamilyPane;
    private javax.swing.JScrollPane FamilyScrollPanel;
    private javax.swing.JPanel FirstMiddleLast;
    private javax.swing.JPanel Gender;
    private javax.swing.JPanel MiscInfo;
    private javax.swing.JButton clearFamily;
    private citibob.jschema.swing.JSchemaTextField customaddressto;
    private citibob.jschema.swing.JSchemaTextField dob;
    private citibob.jschema.swing.JSchemaTextField email;
    private offstage.gui.EntitySubPanel entitySubPanel1;
    private offstage.gui.FamilyTable familyTable;
    private javax.swing.JRadioButton femaleButton;
    private citibob.jschema.swing.JSchemaTextField firstname;
    private citibob.jschema.swing.JSchemaKeyedButtonGroup genderButtonGroup;
    private offstage.gui.IsPrimaryIndicator isPrimaryIndicator1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private citibob.jschema.swing.JSchemaTextField lastname;
    private javax.swing.JRadioButton maleButton;
    private citibob.jschema.swing.JSchemaTextField middlename;
    private citibob.jschema.swing.JSchemaTextField occupation;
    private offstage.gui.GroupPanel phonePanel;
    private citibob.jschema.swing.JSchemaTextField salutation;
    private citibob.jschema.swing.JSchemaTextField title;
    private javax.swing.JRadioButton unknownGenderButton;
    // End of variables declaration//GEN-END:variables
	// --------------------------------------------------------------

}
