/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * EQueryBrowser.java
 *
 * Created on July 3, 2005, 1:31 PM
 */

package offstage.equery.swing;

import java.sql.*;
import java.io.*;
import javax.swing.*;
import citibob.swing.table.*;
import java.util.prefs.*;
import offstage.*;
import offstage.db.FullEntityDbModel;
import offstage.db.EntityListTableModel;
import offstage.equery.*;
import citibob.multithread.*;
import offstage.gui.*;
import citibob.swing.typed.*;
import offstage.db.*;
import citibob.jschema.*;

/**
 *
 * @author  citibob
 */
public class EQueryWiz2 extends javax.swing.JPanel {

SchemaBufDbModel equeryDm;		// Holds our (one) equery
EntityListTableModel testResults;

citibob.app.App fapp;
int queryID;


/** Creates new form EQueryBrowser */
public EQueryWiz2() {
	initComponents();
}

//protected EQueryWiz1 getThis() { return this; }

public void initRuntime(citibob.app.App fapp)
throws SQLException
{
	EQueryTableModel2 eqModel = new EQueryTableModel2(
		new EQuerySchema(fapp.getSchemaSet()));
	eQueryEditor.initRuntime(eqModel, fapp.getSwingerMap());

	equeryDm = new SchemaBufDbModel(new SchemaBuf(fapp.getSchema("equeries")));
	--- Have an easy ad-hoc way to select with an ad-hoc where clause...

	testResults = new EntityListTableModel();
	tTestResults.initRuntime(testResults);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTestResults = new offstage.gui.FamilyTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lQuerySize = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bEdit = new javax.swing.JButton();
        bTransferEntities = new javax.swing.JButton();
        bMakeMailing = new javax.swing.JButton();
        editorPanel = new javax.swing.JPanel();
        eQueryEditor = new offstage.equery.swing.EQueryEditor();
        jTypedTextField1 = new citibob.swing.typed.JTypedTextField();
        jPanel3 = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tTestResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tTestResults);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Number of Records Selected:");
        jPanel2.add(jLabel1);

        lQuerySize.setText("0");
        jPanel2.add(lQuerySize);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        bEdit.setText("Apply");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        jPanel5.add(bEdit);

        bTransferEntities.setText("Edit List");
        bTransferEntities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransferEntitiesActionPerformed(evt);
            }
        });

        jPanel5.add(bTransferEntities);

        bMakeMailing.setText("Make Mailing");
        bMakeMailing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMakeMailingActionPerformed(evt);
            }
        });

        jPanel5.add(bMakeMailing);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jSplitPane4.setRightComponent(jPanel1);

        editorPanel.setLayout(new java.awt.BorderLayout());

        eQueryEditor.setColName("equery");
        editorPanel.add(eQueryEditor, java.awt.BorderLayout.CENTER);

        jTypedTextField1.setText("jTypedTextField1");
        jTypedTextField1.setColName("name");
        editorPanel.add(jTypedTextField1, java.awt.BorderLayout.NORTH);

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        jPanel3.add(bOK);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jPanel3.add(bCancel);

        editorPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jSplitPane4.setTopComponent(editorPanel);

        add(jSplitPane4, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bOKActionPerformed

private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bEditActionPerformed

	private void bTransferEntitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransferEntitiesActionPerformed
		runner.doRun(new StRunnable() {
		public void run(Statement st) throws Exception {
			EntityListTableModel res = fapp.getSimpleSearchResults();
			EQuery eqy = app.oneQueryTableModel.getQuery();
			String sql = eqy.getSql(app.schema);
			res.setRows(st, sql, null);
			fapp.setScreen(FrontApp.PEOPLE_SCREEN);
		}});
	}//GEN-LAST:event_bTransferEntitiesActionPerformed

private void bMakeMailingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMakeMailingActionPerformed
	runner.doRun(new StRunnable() {
	public void run(Statement st) throws Exception {
		app.makeMailing(st, app.oneQueryTableModel.getQuery(),
			(String)app.oneQueryRow.get(app.oneQueryRow.findColumn("name")));
		fapp.setScreen(FrontApp.MAILINGS_SCREEN);
	}});
}//GEN-LAST:event_bMakeMailingActionPerformed

private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
	runner.doRun(new ERunnable() {
	public void run() throws Exception {
		app.undoCurQuery();
	}});
}//GEN-LAST:event_bCancelActionPerformed

void saveCurQuery(Statement st) throws Exception
{
		eQueryEditor.commitValue();
		app.saveCurQuery(st);	
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bMakeMailing;
    private javax.swing.JButton bOK;
    private javax.swing.JButton bTransferEntities;
    private offstage.equery.swing.EQueryEditor eQueryEditor;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane4;
    private citibob.swing.typed.JTypedTextField jTypedTextField1;
    private javax.swing.JLabel lQuerySize;
    private offstage.gui.FamilyTable tTestResults;
    // End of variables declaration//GEN-END:variables
// ================================================================

}
