/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * EQueryEditor.java
 *
 * Created on July 2, 2005, 11:41 AM
 */

package offstage.equery.swing;

import citibob.swing.*;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.event.*;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import citibob.jschema.*;
import offstage.equery.*;

/**
 *
 * @author  citibob
 */
public class EQueryEditor extends javax.swing.JPanel {

	EQueryTableModel2 model;

    /** Creates new form EQueryEditor */
    public EQueryEditor() {
        initComponents();
		
		eClauseScrollPane.setRowHeaderView(new TableRowHeader(eClauseScrollPane, eQueryTable, 15));
    }

	public void initRuntime(EQueryTableModel2 qm, SwingerMap smap)
	throws SQLException
	{
		this.model = qm;
		eQueryTable.setModel(qm);
		eQueryTable.setSwingerMap(smap);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        eClauseScrollPane = new javax.swing.JScrollPane();
        eQueryTable = new offstage.equery.swing.EQueryTable();
        jToolBar1 = new javax.swing.JToolBar();
        bAddClause = new javax.swing.JButton();
        bAddElement = new javax.swing.JButton();
        bRemoveRow = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        eQueryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eClauseScrollPane.setViewportView(eQueryTable);

        add(eClauseScrollPane, java.awt.BorderLayout.CENTER);

        bAddClause.setText("+Clause");
        bAddClause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddClauseActionPerformed(evt);
            }
        });

        jToolBar1.add(bAddClause);

        bAddElement.setText("+Element");
        bAddElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddElementActionPerformed(evt);
            }
        });

        jToolBar1.add(bAddElement);

        bRemoveRow.setText("-");
        bRemoveRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveRowActionPerformed(evt);
            }
        });

        jToolBar1.add(bRemoveRow);

        add(jToolBar1, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

public int getSelectedRow()
{
	ListSelectionModel lsm = eQueryTable.getSelectionModel();
	if (lsm.isSelectionEmpty()) {
		return -1;
	} else {
		int selectedRow = lsm.getMinSelectionIndex();
		return selectedRow;
	}
	put this in jtypetable?
}
	
	private void bAddClauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddClauseActionPerformed
	model.insertClause(getSelectedRow(), new Clause());
	}//GEN-LAST:event_bAddClauseActionPerformed

	private void bRemoveRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveRowActionPerformed
	model.removeRow(getSelectedRow());
	}//GEN-LAST:event_bRemoveRowActionPerformed

private void bAddElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddElementActionPerformed
	model.insertElement(getSelectedRow(), new Element());
}//GEN-LAST:event_bAddElementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddClause;
    private javax.swing.JButton bAddElement;
    private javax.swing.JButton bRemoveRow;
    private javax.swing.JScrollPane eClauseScrollPane;
    private offstage.equery.swing.EQueryTable eQueryTable;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
