/*
Offstage CRM: Enterprise Database for Arts Organizations
This file Copyright (c) 2006 by Robert Fischer

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/*
 * EQueryBrowser.java
 *
 * Created on July 3, 2005, 1:31 PM
 */

package offstage.equery.swing;

import java.sql.*;
import java.io.*;
import javax.swing.*;
import citibob.jschema.*;
import citibob.swing.table.*;
import java.util.prefs.*;
import offstage.*;
import citibob.multithread.*;
import offstage.gui.*;
import citibob.swing.typed.*;
import offstage.db.*;

/**
 *
 * @author  citibob
 */
public class EQueryWiz1 extends javax.swing.JDialog {

FrontApp fapp;
EQueryModel2 app;
EntityListTableModel testResults;
//Statement st;
ActionRunner runner;

SchemaBufDbModel equeriesDm;
public boolean ok = false;		// Did user exit by pressing OK?
public int equeryID;			// Query ID selected by user

/** Creates new form EQueryBrowser */
public EQueryWiz1(java.awt.Frame frame) {
	super(frame, "Select Query", true);
	initComponents();
}

public void initRuntime(final citibob.app.App fapp)
throws SQLException
{
	equeriesDm = tQueries.setSubSchemaDm(fapp.getSchema("equeries"),
		new String[] {"ID", "Name", "Modified"},
		new String[] {"equeryid", "name", "lastmodified"},
		new boolean[] {false, false, false},
		fapp.getSwingerMap());

	tQueries.addMouseListener(new DClickTableMouseListener(tQueries) {
	public void doubleClicked(final int row) {
		fapp.runGui(new StRunnable() {
		public void run(Statement st) throws Exception {
			tQueries.getSelectionModel().setSelectionInterval(row, row);
			finishDialog(true);
		}});
	}});
}

void finishDialog(boolean b)
{
	int row = tQueries.getSelectionModel().getMinSelectionIndex();
	if (row < 0 && b) return;	// Must select something first.
	equeryID = (Integer)equeriesDm.getSchemaBuf().getValueAt(row, 0);
	ok = b;
	setVisible(false);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane3 = new javax.swing.JScrollPane();
        tQueries = new citibob.jschema.swing.SchemaBufTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tQueries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tQueries);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Please select the query below you wish to edit.");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        jPanel1.add(bOK);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jPanel1.add(bCancel);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
	finishDialog(false);
}//GEN-LAST:event_bCancelActionPerformed

private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
	finishDialog(true);
}//GEN-LAST:event_bOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private citibob.jschema.swing.SchemaBufTable tQueries;
    // End of variables declaration//GEN-END:variables
// ================================================================

}
