/*
 * NewJPanel.java
 *
 * Created on September 24, 2006, 7:30 PM
 */

package offstage.equery.swing;

/**
 *
 * @author  citibob
 */
public class NewJPanel extends javax.swing.JPanel {
	
	/** Creates new form NewJPanel */
	public NewJPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        eQueryTable1 = new offstage.equery.swing.EQueryTable();

        setLayout(new java.awt.BorderLayout());

        eQueryTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        add(eQueryTable1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.equery.swing.EQueryTable eQueryTable1;
    // End of variables declaration//GEN-END:variables
	
}
