/*
 * CoursesPanel.java
 *
 * Created on December 15, 2007, 4:39 PM
 */

package offstage.school.gui;

import citibob.jschema.DbModel;
import citibob.jschema.IntKeyedDbModel;
import citibob.jschema.MultiDbModel;
import citibob.jschema.SchemaBufRowModel;
import citibob.multithread.BatchRunnable;
import citibob.multithread.ERunnable;
import citibob.sql.SqlRunner;
import citibob.swing.RowModel;
import citibob.swing.table.RowModelTableModel;
import offstage.FrontApp;

/**
 *
 * @author  citibob
 */
public class TermsPanel extends javax.swing.JPanel
{
	
FrontApp fapp;
SchoolModel smod;

IntKeyedDbModel oneTermDm;
	RowModel oneTermRm;
IntKeyedDbModel duedatesDm;
IntKeyedDbModel holidaysDm;

MultiDbModel allDm;

/** Creates new form CoursesPanel */
public TermsPanel()
{
	initComponents();
}

	

/** Creates new form CompleteStatusPanel */
public void initRuntime(FrontApp xfapp, SchoolModel smod, SqlRunner str)
//throws SQLException
{
	this.fapp = xfapp;
	this.smod = smod;

	smod.addListener(new SchoolModel.Adapter() {
    public void termIDChanged(int oldTermID, int termID) {
			termChanged(fapp.getBatchSet());
	}});

	
	oneTermDm = new IntKeyedDbModel(fapp.getSchema("termids"),
		"groupid", fapp.getDbChange(), new IntKeyedDbModel.Params(false));
	oneTermRm = new SchemaBufRowModel(oneTermDm.getSchemaBuf());
	
	termInfo.setSwingerMap(fapp.getSwingerMap());
	termInfo.setModel(new RowModelTableModel(oneTermRm,
		new String[] {"Name", "Type", "From", "To (+1)", "Current?"},
		new String[] {"name", "termtypeid", "firstdate", "nextdate", "iscurrent"}));

	duedatesDm = new IntKeyedDbModel(fapp.getSchema("termduedates"),
		"termid", fapp.getDbChange(), new IntKeyedDbModel.Params(false));
	duedates.setModelU(duedatesDm.getSchemaBuf(),
		new String[] {"Status", "Name", "Due Date", "Description"},
		new String[] {"__status__", "name", "duedate", "description"},
		null, fapp.getSwingerMap());
	
	holidaysDm = new IntKeyedDbModel(fapp.getSchema("holidays"),
		"termid", fapp.getDbChange(), new IntKeyedDbModel.Params(false));
	holidays.setModelU(holidaysDm.getSchemaBuf(),
		new String[] {"Status", "First Day", "Last Day", "Description"},
		new String[] {"__status__", "firstday", "lastday", "description"},
		null, fapp.getSwingerMap());
	
	allDm = new MultiDbModel(new DbModel[] {oneTermDm, duedatesDm, holidaysDm});
}

void termChanged(SqlRunner str) 
{
	Integer Termid = (Integer)smod.getTermID();
	allDm.doUpdate(str);
	allDm.setKey(Termid);
	allDm.doSelect(str);
}

	
void all_doSelect(SqlRunner str)
{
	allDm.doSelect(str);
}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        termInfo = new citibob.swing.JTypeTable();
        duedatesPane = new javax.swing.JScrollPane();
        duedates = new citibob.jschema.swing.SchemaBufTable();
        duedatesButtons = new javax.swing.JPanel();
        ddAdd = new javax.swing.JButton();
        ddDel = new javax.swing.JButton();
        ddUndel = new javax.swing.JButton();
        holidaysPane = new javax.swing.JScrollPane();
        holidays = new citibob.jschema.swing.SchemaBufTable();
        holidaysButtons = new javax.swing.JPanel();
        holAdd = new javax.swing.JButton();
        holDel = new javax.swing.JButton();
        holUndel = new javax.swing.JButton();
        lDueDate = new javax.swing.JLabel();
        lHolidays = new javax.swing.JLabel();
        lTermInfo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bSave = new javax.swing.JButton();
        bUndo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        termInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanel2.add(termInfo, gridBagConstraints);

        duedates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        duedatesPane.setViewportView(duedates);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(duedatesPane, gridBagConstraints);

        ddAdd.setText("Add");
        ddAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ddAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ddAddActionPerformed(evt);
            }
        });

        duedatesButtons.add(ddAdd);

        ddDel.setText("Del");
        ddDel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ddDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ddDelActionPerformed(evt);
            }
        });

        duedatesButtons.add(ddDel);

        ddUndel.setText("(Undo)");
        ddUndel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ddUndel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ddUndelActionPerformed(evt);
            }
        });

        duedatesButtons.add(ddUndel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        jPanel2.add(duedatesButtons, gridBagConstraints);

        holidaysPane.setPreferredSize(new java.awt.Dimension(300, 275));
        holidays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        holidaysPane.setViewportView(holidays);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(holidaysPane, gridBagConstraints);

        holAdd.setText("Add");
        holAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holAddActionPerformed(evt);
            }
        });

        holidaysButtons.add(holAdd);

        holDel.setText("Del");
        holDel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holDelActionPerformed(evt);
            }
        });

        holidaysButtons.add(holDel);

        holUndel.setText("(Undo)");
        holUndel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holUndel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holUndelActionPerformed(evt);
            }
        });

        holidaysButtons.add(holUndel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(holidaysButtons, gridBagConstraints);

        lDueDate.setText("Due Dates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lDueDate, gridBagConstraints);

        lHolidays.setText("Holidays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lHolidays, gridBagConstraints);

        lTermInfo.setText("Term Parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lTermInfo, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bSaveActionPerformed(evt);
            }
        });

        jToolBar1.add(bSave);

        bUndo.setText("Undo");
        bUndo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bUndoActionPerformed(evt);
            }
        });

        jToolBar1.add(bUndo);

        add(jToolBar1, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

	private void ddUndelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ddUndelActionPerformed
	{//GEN-HEADEREND:event_ddUndelActionPerformed
		fapp.runGui(TermsPanel.this, new ERunnable() {
		public void run() throws Exception {
			duedatesDm.getSchemaBuf().undeleteRow(duedates.getSelectedRow());
			duedates.requestFocus();
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_ddUndelActionPerformed

	private void holUndelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holUndelActionPerformed
	{//GEN-HEADEREND:event_holUndelActionPerformed
		fapp.runGui(TermsPanel.this, new ERunnable() {
		public void run() throws Exception {
			holidaysDm.getSchemaBuf().undeleteRow(holidays.getSelectedRow());
			holidays.requestFocus();
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_holUndelActionPerformed

	private void bUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bUndoActionPerformed
	{//GEN-HEADEREND:event_bUndoActionPerformed
		fapp.runApp(new BatchRunnable() {
		public void run(SqlRunner str) throws Exception {
			all_doSelect(str);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_bUndoActionPerformed

	private void bSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bSaveActionPerformed
	{//GEN-HEADEREND:event_bSaveActionPerformed
		fapp.runApp(new BatchRunnable() {
		public void run(SqlRunner str) throws Exception {
			allDm.doUpdate(str);
			str.flush();
			all_doSelect(str);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_bSaveActionPerformed

	private void holDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holDelActionPerformed
	{//GEN-HEADEREND:event_holDelActionPerformed
		fapp.runGui(TermsPanel.this, new ERunnable() {
		public void run() throws Exception {
			holidaysDm.getSchemaBuf().deleteRow(holidays.getSelectedRow());
			holidays.requestFocus();
		}});
	}//GEN-LAST:event_holDelActionPerformed

	private void holAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holAddActionPerformed
	{//GEN-HEADEREND:event_holAddActionPerformed
		fapp.runGui(TermsPanel.this, new BatchRunnable() {
		public void run(SqlRunner str) throws Exception {
			holidaysDm.getSchemaBuf().insertRow(-1, "termid", (Integer)smod.getTermID());
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_holAddActionPerformed

	private void ddDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ddDelActionPerformed
	{//GEN-HEADEREND:event_ddDelActionPerformed
		fapp.runGui(TermsPanel.this, new ERunnable() {
		public void run() throws Exception {
			duedatesDm.getSchemaBuf().deleteRow(duedates.getSelectedRow());
			duedates.requestFocus();
		}});
	}//GEN-LAST:event_ddDelActionPerformed

	private void ddAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ddAddActionPerformed
	{//GEN-HEADEREND:event_ddAddActionPerformed
		fapp.runGui(TermsPanel.this, new ERunnable() {
		public void run() throws Exception {
			duedatesDm.getSchemaBuf().insertRow(-1, "termid", (Integer)smod.getTermID());
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_ddAddActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUndo;
    private javax.swing.JButton ddAdd;
    private javax.swing.JButton ddDel;
    private javax.swing.JButton ddUndel;
    private citibob.jschema.swing.SchemaBufTable duedates;
    private javax.swing.JPanel duedatesButtons;
    private javax.swing.JScrollPane duedatesPane;
    private javax.swing.JButton holAdd;
    private javax.swing.JButton holDel;
    private javax.swing.JButton holUndel;
    private citibob.jschema.swing.SchemaBufTable holidays;
    private javax.swing.JPanel holidaysButtons;
    private javax.swing.JScrollPane holidaysPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lDueDate;
    private javax.swing.JLabel lHolidays;
    private javax.swing.JLabel lTermInfo;
    private citibob.swing.JTypeTable termInfo;
    // End of variables declaration//GEN-END:variables
	
}
