/*
 * DupCheckPanel.java
 *
 * Created on October 12, 2006, 8:31 PM
 */

package offstage.wizards.newrecord;

import offstage.db.*;
import offstage.*;
import citibob.multithread.*;
import citibob.swing.typed.*;
import java.sql.*;
import citibob.swing.*;
import citibob.swing.table.*;
import citibob.app.*;

/**
 *
 * @author  citibob
 */
public class IDListViewer extends javax.swing.JPanel {

FullEntityDbModel entityDb;
EntityListTableModel dupsModel;

/** Creates new form DupCheckPanel */
public IDListViewer() {
	initComponents();
}

//public void initRuntime(Statement st,
//EntityListTableModel dupsModel, FullEntityDbModel entityDb,
//ActionRunner guiRunner, SwingerMap smap)
//{
//	this.dupsModel = dupsModel;
//	this.entityDb = entityDb;
//}

public void initRuntime(Statement st,
FullEntityDbModel xentityDb,
String idSql, String orderBy,
final App app)
//final ActionRunner guiRunner, SwingerMap smap)
throws SQLException
{
//	final App app = xapp;
//	final ActionRunner guiRunner = app.getGuiRunner();
	dupsModel = new EntityListTableModel(app.getSqlTypeSet());
	dupsModel.setRows(st, idSql, orderBy);
	this.entityDb = xentityDb;
	dupsTable.initRuntime(dupsModel);
	mainEntityPanel.initRuntime(st, app, entityDb);
	DClickTableMouseListener dclick =
		new DClickTableMouseListener(dupsTable) {
		public void doubleClicked(final int row) {
			app.runGui(IDListViewer.this, new StRunnable() {
			public void run(Statement st) throws Exception {
				// Make sure it's selected in the GUI
				dupsTable.getSelectionModel().setSelectionInterval(row, row);

				// Process the selection
				int entityid = getSelectedEntityID(dupsTable);
				if (entityid < 0) return;
				entityDb.setKey(entityid);
				entityDb.doSelect(st);
			}});
		}};
	
	// Double-clicking will go to selected person
	dupsTable.addMouseListener(dclick);
	dclick.doubleClicked(0);		// There's at least one row here, select it.

}

int getSelectedEntityID(CitibobJTable searchResultsTable)
{
	int selected = searchResultsTable.getSelectedRow();
	if (selected < 0) return -1;
	int entityID = dupsModel.getEntityID(selected);
	return entityID;
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dupsTable = new offstage.gui.FamilyTable();
        mainEntityPanel = new offstage.gui.MainEntityPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(200);
        dupsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dupsTable);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jSplitPane2.setRightComponent(mainEntityPanel);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.gui.FamilyTable dupsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private offstage.gui.MainEntityPanel mainEntityPanel;
    // End of variables declaration//GEN-END:variables

}
