/*
 * CoursesEditor.java
 *
 * Created on June 8, 2007, 10:08 PM
 */

package offstage.wizard.editcourses;

import java.sql.*;
import citibob.jschema.*;
import citibob.jschema.swing.*;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import citibob.multithread.*;
import citibob.jschema.swing.StatusTable;
import citibob.sql.*;
import citibob.app.*;
import offstage.*;
import java.awt.event.*;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import citibob.util.*;
import java.util.*;
import citibob.sql.pgsql.*;
import citibob.swing.pgsql.*;
import citibob.sql.*;

/**
 *
 * @author  citibob
 */
public class CoursesWiz extends citibob.swing.JPanelWiz
{

IntKeyedDbModel coursesSb;
FrontApp fapp;

	/** Creates new form CompleteStatusPanel */
	public CoursesWiz(FrontApp xfapp, Statement xst, int termid)
	throws SQLException
	{
		super("Edit Courses");
		initComponents();
		this.fapp = xfapp;
		
		// Set up terms selector
		terms.setKeyedModel(new DbKeyedModel(xst, fapp.getDbChange(), "termids",
			"select termid, name from termids where iscurrent order by firstdate"));
		terms.addPropertyChangeListener("value", new PropertyChangeListener() {
	    public void propertyChange(PropertyChangeEvent evt) {
			fapp.runApp(new StRunnable() {
			public void run(Statement st) throws Exception {
				coursesSb.doUpdate(st);
				coursesSb.setKey((Integer)terms.getValue());
				coursesSb.doSelect(st);
			}});
		}});
		
		// Set up courses editor
		coursesSb = new IntKeyedDbModel(fapp.getSchema("courseids"),
			"termid", fapp.getDbChange());
		terms.setSelectedIndex(0);		// Should throw a value changed event
		courses.setModelU(coursesSb.getSchemaBuf(),
			new String[] {"Name", "Day", "Start", "End", "Enroll Limit"},
			new String[] {"name", "dayofweek", "tstart", "tnext", "enrolllimit"},
			null, fapp.getSwingerMap());
//		courses.setRowSelectionAllowed(false);

//courses.setRowSelectionAllowed(false);
//courses.setColumnSelectionAllowed(false);
//courses.setCellSelectionEnabled(false);

//		public void setModelU(SchemaBuf schemaBuf,
//String[] xColNames, String[] xSColMap,
//boolean[] xEditable, SwingerMap swingers)

		KeyedModel dkm = new DayOfWeekKeyedModel();
		courses.setRenderEditU("dayofweek", new KeyedRenderEdit(dkm));

		Swinger swing = new SqlTimeSwinger(true, "HH:mm");
		courses.setRenderEditU("tstart", swing);
		courses.setRenderEditU("tnext", swing);
		
//		KeyedRenderEdit tkre = new KeyedRenderEdit(new TimeSKeyedModel(7,0, 23,0, 15*60));
//		courses.setRenderEditU("tstart_s", tkre);
//		courses.setRenderEditU("tnext_s", tkre);
		terms.setValue(termid);
	}
	
	/** After the Wiz is done running, report its output into a Map. */
	public void getAllValues(java.util.Map map)
	{
		Object courseid = courses.getOneSelectedValU("courseid");
		map.put("courseid", courseid);
	}

	public void backPressed() { saveCur(); }
	public void nextPressed() { saveCur(); }

	public void saveCur()
	{
		fapp.runGui(CoursesWiz.this, new StRunnable() {
		public void run(Statement st) throws Exception {
			if (coursesSb.valueChanged()) {
				coursesSb.doUpdate(st);
				coursesSb.doSelect(st);
			}
		}});
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        bAdd = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bRestore = new javax.swing.JButton();
        bMeetings = new javax.swing.JButton();
        bDone = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses = new citibob.jschema.swing.StatusTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        terms = new citibob.swing.typed.JKeyedComboBox();

        setLayout(new java.awt.BorderLayout());

        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bAddActionPerformed(evt);
            }
        });

        jPanel1.add(bAdd);

        bDel.setText("Del");
        bDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bDelActionPerformed(evt);
            }
        });

        jPanel1.add(bDel);

        bRestore.setText("Restore");
        bRestore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bRestoreActionPerformed(evt);
            }
        });

        jPanel1.add(bRestore);

        bMeetings.setText(">>Meetings");
        bMeetings.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bMeetingsActionPerformed(evt);
            }
        });

        jPanel1.add(bMeetings);

        bDone.setText("Done");
        bDone.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bDoneActionPerformed(evt);
            }
        });

        jPanel1.add(bDone);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(courses);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Term: ");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        terms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(terms, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents

	private void bMeetingsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bMeetingsActionPerformed
	{//GEN-HEADEREND:event_bMeetingsActionPerformed
		fapp.runGui(CoursesWiz.this, new StRunnable() {
		public void run(Statement st) throws Exception {
			  coursesSb.doUpdate(st);
			  coursesSb.doSelect(st);
			  citibob.swing.WidgetTree.getRoot(CoursesWiz.this).setVisible(false);
		  }});
// TODO add your handling code here:
	}//GEN-LAST:event_bMeetingsActionPerformed

	private void bDoneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bDoneActionPerformed
	{//GEN-HEADEREND:event_bDoneActionPerformed
		fapp.runGui(CoursesWiz.this, new StRunnable() {
		public void run(Statement st) throws Exception {
			  coursesSb.doUpdate(st);
//			  coursesSb.doSelect(st);
			  citibob.swing.WidgetTree.getRoot(CoursesWiz.this).setVisible(false);
		  }});
// TODO add your handling code here:
	}//GEN-LAST:event_bDoneActionPerformed

	private void bRestoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bRestoreActionPerformed
	{//GEN-HEADEREND:event_bRestoreActionPerformed
		fapp.runGui(CoursesWiz.this, new StRunnable()
		{ public void run(Statement st) throws Exception
		  {
			  coursesSb.doSelect(st);
		  }});
// TODO add your handling code here:
	}//GEN-LAST:event_bRestoreActionPerformed

	private void bDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bDelActionPerformed
	{//GEN-HEADEREND:event_bDelActionPerformed
		fapp.runGui(CoursesWiz.this, new ERunnable()
		{ public void run() throws Exception
		  {
			  int selected = courses.getSelectedRow();
			  if (selected != -1) {
				  coursesSb.getSchemaBuf().deleteRow(selected);
			  }
		  }});
	}//GEN-LAST:event_bDelActionPerformed

	private void bAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bAddActionPerformed
	{//GEN-HEADEREND:event_bAddActionPerformed
		fapp.runGui(CoursesWiz.this, new ERunnable()
		{ public void run() throws Exception
		  {
			  coursesSb.getSchemaBuf().insertRow(-1);
		  }});
// TODO add your handling code here:
	}//GEN-LAST:event_bAddActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bDone;
    private javax.swing.JButton bMeetings;
    private javax.swing.JButton bRestore;
    private citibob.jschema.swing.StatusTable courses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private citibob.swing.typed.JKeyedComboBox terms;
    // End of variables declaration//GEN-END:variables
	
}
