/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2007 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * DBTest2.java
 *
 * Created on July 24, 2005, 9:22 PM
 */

package offstage.db;

import java.sql.*;
import offstage.db.TestConnPool;

/**
 *
 * @author  citibob
 */
public class DBTest2 extends javax.swing.JFrame {
	
	/** Creates new form DBTest2 */
	public DBTest2() throws Exception {
		initComponents();
		Connection db = new TestConnPool().checkout();
		Statement st = db.createStatement();
		ResultSet rs = st.executeQuery(
				"select addressto from aapeople where addressto like '%Adelina%'");
		while (rs.next()) {
			String s1 = rs.getString(1);
			byte[] bt = rs.getBytes(1);
			String s2 = new String(bt,"UTF-8");
			System.out.println(s1.equals(s2) + ", " + s1.length() +", " + bt.length);
			jLabel1.setText(s1);
			jLabel2.setText(s2);
			for (int i=0; i<s1.length(); ++i)
				System.out.print((int)s1.charAt(i) + " ");
				System.out.println("");
		}
		rs.close();
		String ss="\u0042\u0069\u0065\u006E\u0076" +
         "\u0065\u006E\u0075\u0065\u0020\u0061\u0075\u0020\u00e9";
		jLabel1.setText(ss);
		System.out.println(ss);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(345, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(245, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(245, 15));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("jLabel2");
        jLabel2.setMinimumSize(new java.awt.Dimension(245, 15));
        getContentPane().add(jLabel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) throws Exception {

		DBTest2 db = new DBTest2();
		db.setVisible(true);
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
	
}
